// lib/core/services/location_service.dart

class LocalizedItem {
  final String id;
  final String nameEn;
  final String nameLc;

  LocalizedItem(this.id, this.nameEn, this.nameLc);
  String getName(bool isMarathi) => isMarathi ? nameLc : nameEn;
}

class LocationService {
  // ---------------------------------------------------------
  // ✅ UPDATED HARDCODED DATA
  // ---------------------------------------------------------
  static final Map<String, Map<String, Map<String, List<String>>>> _data = {
    "Maharashtra": {
      "Nashik": {
        "Baglan": [
          "Ajande Digar",
          "Ajmir Saundane",
          "Akhatwade",
          "Aliyabad",
          "Ambapur",
          "Ambasan",
          "Anandpur",
          "Antapur",
          "Arai",
          "Askheda",
          "Aundane",
          "Avhati",
          "Babhulane",
          "Bahirane",
          "Bhadane",
          "Bhakshi",
          "Bhavnagar",
          "Bhawade",
          "Bhildar",
          "Bhilwad",
          "Bhimkhet",
          "Bhimnagar",
          "Bhuyane",
          "Bijorase",
          "Bijote",
          "Bilpuri",
          "Bodhari",
          "Bordaiwat",
          "Borhate Digar",
          "Bramhangaon",
          "Bramhanpade",
          "Bundhate",
          "Chaugaon",
          "Chaundhane",
          "Chirai",
          "Dagadpada",
          "Dahindule",
          "Dangsaundane",
          "Daregaon",
          "Darhane",
          "Dasane",
          "Daswel",
          "Deolane",
          "Deopur",
          "Deopur(Chafyachepade)",
          "Deothan-Digar",
          "Dhandri",
          "Dholbare",
          "Dodheshwar",
          "Dongrej",
          "Dyane",
          "Eklahare",
          "Fopir",
          "Gandhinagar",
          "Ganeshnagar",
          "Gautamnagar",
          "Golwad",
          "Gorane",
          "Hatnoor",
          "Ijamane",
          "Indiranagar",
          "Jad",
          "Jaikheda",
          "Jaipur",
          "Jaitapur",
          "Jakhod",
          "Jamoti",
          "Joran",
          "June Nirpur",
          "Juni Shemali",
          "Kadyachamala",
          "Kakadgaon",
          "Kandhane",
          "Kapaleshwar",
          "Karanjad",
          "Karanjkhed",
          "Karhe",
          "Katarwel",
          "Kathagad",
          "Kautikpada",
          "Kelzar",
          "Kersane",
          "Khamlon",
          "Khamtane",
          "Kharad",
          "Khirmani",
          "Kikwari Bk.",
          "Kikwari Kh.",
          "Kodharabad",
          "Kodmal",
          "Korobanagar",
          "Kotbel",
          "Kupkhede",
          "Ladud",
          "Lakhamapur",
          "Mahad",
          "Mahatma Phule Nagar",
          "Mailwade",
          "Malegaon Tilwan",
          "Malgaon Bhamer",
          "Malgaon Kh.",
          "Manur",
          "Moholangi",
          "Morane Digar",
          "Morane Sandas",
          "More Nagar",
          "Morkure",
          "Mulane",
          "Mulher",
          "Mungase",
          "Munjwad",
          "Nalkas",
          "Nampur",
          "Nandin",
          "Narkol",
          "Navegaon",
          "Nave Nirpur",
          "Navi Shemali",
          "Nikwel",
          "Nitane",
          "Parner",
          "Parshuramnagar",
          "Pathave Digar",
          "Pimpaldar",
          "Pimpalkothe",
          "Pingalwade",
          "Pisore",
          "Rahud",
          "Rajpurpande",
          "Ramtir",
          "Ratir",
          "Raver",
          "Sakode",
          "Salher",
          "Salwan",
          "Sarade",
          "Sarpargaon",
          "Sarwar",
          "Satana 1",
          "Shevare",
          "Shripurvade",
          "Sompur",
          "Statana 2",
          "Surane",
          "Taharabad",
          "Talwade Bhamer",
          "Talwade Digar",
          "Tandulwadi",
          "Tarsali",
          "Tatani",
          "Tembhe Khalche",
          "Tembhe (Varche)",
          "Thengoda",
          "Tilwan",
          "Tinghari",
          "Tungan Digar",
          "Utrane",
          "Vade Digar",
          "Vade Kh.",
          "Vanoli",
          "Vatar",
          "Vathode",
          "Vaygaon",
          "Vijaynagar",
          "Vinchure",
          "Virgaon",
          "Visapur",
          "Wadi Chaulher",
          "Wadipisol",
          "Waghale",
          "Waghambe",
          "Yashawantnagar"
        ],
        "Chandvad": [
          "Adgaon",
          "Ahirkhede",
          "Asarkhede",
          "Bahaduri",
          "Bhadane",
          "Bharvir",
          "Bhatgaon",
          "Bhayale",
          "Bhoyegaon",
          "Bhutyane",
          "Bopane",
          "Borale",
          "Chandvad",
          "Chikhalambe",
          "Chinchole",
          "Dahegaon Ma.",
          "Dahiwad",
          "Dahyane",
          "Daregaon",
          "Deogaon",
          "Devargaon",
          "Dhodambe",
          "Dhondgavhan",
          "Dhotarkhede",
          "Dighwad",
          "Dongaon",
          "Dongargaon",
          "Dudhkhede",
          "Dugaon",
          "Ekrukhe",
          "Gangave",
          "Ganur",
          "Goharan",
          "Gurhale",
          "Harnul",
          "Harsul",
          "Hatti",
          "Hirapur",
          "Hivarkhede",
          "Indira Nagar",
          "Indrayanwadi",
          "Jaitapur",
          "Jambutke",
          "Jopul",
          "Kajisangvi",
          "Kalamdare",
          "Kalkhode",
          "Kanadgaon",
          "Kanmandale",
          "Katarwadi",
          "Khadakjamb",
          "Khadakozar",
          "Kheldari",
          "Kokankhede",
          "Koltek",
          "Kundalgaon",
          "Kundane",
          "Malsane",
          "Mangrul",
          "Mesankhede Bk.",
          "Mesankhede Kh",
          "Nandurtek",
          "Narayangaon",
          "Narayankhede",
          "Nawapur",
          "Nhanave",
          "Nimbale",
          "Nimgavhan",
          "Nimon",
          "Panhale",
          "Paregaon",
          "Parsul",
          "Pate",
          "Patharshembe",
          "Pimpalgaon Dhabli",
          "Pimpalnare",
          "Pimplad",
          "Puri",
          "Rahod",
          "Rajderwadi",
          "Rapali",
          "Raypur",
          "Redgaon Kh",
          "Salsane",
          "Shelu",
          "Sherisalaiban",
          "Shinde",
          "Shingve",
          "Shirsane",
          "Shirur",
          "Shivajinagar",
          "Shivare",
          "Sogras",
          "Soni Sangvi",
          "Sutarkhede",
          "Talegaon Rohi",
          "Talwade",
          "Tisgaon",
          "Urdhul",
          "Uswad",
          "Vad",
          "Vadalibhoi",
          "Vadbare",
          "Vadgaon Pangu",
          "Vadner Bhairao",
          "Vahegaon Sal",
          "Vaki Bk",
          "Vaki Kh",
          "Varadi",
          "Vijaynagar",
          "Vitave",
          "Wakdardi"
        ],
        "Deola": [
          "Bhaur",
          "Bhavade",
          "Bhilwad",
          "Chinchave (Ni.)",
          "Dahiwad",
          "Deola",
          "Deopurpada",
          "Dongargaon",
          "Fulemalwadi",
          "Giranare",
          "Gunjalnagar",
          "Hanmantpada",
          "Kanchane",
          "Kankapur",
          "Kapashi",
          "Khadaktale",
          "Khalap",
          "Khamkhede",
          "Kharde (Wa.)",
          "Kumbharde",
          "Lohaner",
          "Ma. Fulenagar",
          "Mahalpatane",
          "Malwadi",
          "Matane",
          "Meshi",
          "Nimbole",
          "Phule Nagar",
          "Pimpalgaon",
          "Rameshwar",
          "Ramnagar",
          "Sangavi",
          "Satwaichiwadi",
          "Savaki Lo",
          "Sheri(Lo)",
          "Subhashnagar",
          "Tisgaon",
          "Umarane",
          "Varhale",
          "Vasol",
          "Vithewadi",
          "Wadale (Wa.)",
          "Wajgaon",
          "Wakhari",
          "Warshi",
          "Warwandi"
        ],
        "Dindori": [
          "Ahiwantwadi",
          "Akrale",
          "Ambad",
          "Ambaner",
          "Ambedindori",
          "Ambegaon",
          "Ambevani",
          "Awankhed",
          "Babapur",
          "Badagichapada",
          "Bandharpada",
          "Bhanwad",
          "Bhatode",
          "Bopegaon",
          "Borvan",
          "Chachadgaon",
          "Chamdari",
          "Chandikapur",
          "Charose",
          "Chausale",
          "Chikadi",
          "Chilharpada",
          "Chinchkhed",
          "Dagadpimpri",
          "Dahegaon",
          "Dahivi",
          "Dehare",
          "Deherewadi",
          "Deoghar",
          "Deolichapada",
          "Deopada",
          "Deosane",
          "Deothan",
          "Devapur",
          "Dhakambe",
          "Dhamanwadi",
          "Dhaur",
          "Dhondalpada",
          "Dindori 1",
          "Dindori 2",
          "Eklahare",
          "Gandole",
          "Ganeshgaon",
          "Gawalwadi",
          "Ghodewadi",
          "Goldari",
          "Golshi",
          "Gondegaon",
          "Haste Dumala",
          "Hatnore",
          "Indore",
          "Jalkhed",
          "Jambutake",
          "Janori",
          "Jaulakedindori",
          "Jaulakevani",
          "Jirwade",
          "Jopul",
          "Joran",
          "Joranpada",
          "June Dhagur",
          "Kadawa Mhalungi",
          "Karanjali",
          "Karanjkhed",
          "Karanjwan",
          "Kasbe Vani",
          "Kaudasar",
          "Khadak Sukene",
          "Khatwad",
          "Khedale",
          "Khedgaon",
          "Khoripada",
          "Kochargaon",
          "Kokangaon Bk.",
          "Kokangaon Kh.",
          "Kolher",
          "Korhate",
          "Koshimbe",
          "Krishnagaon",
          "Kurnoli",
          "Lakhamapur",
          "Lokhandewadi",
          "Madakijamb",
          "Mahaje",
          "Maledumala",
          "Malegaonkazi",
          "Mandane",
          "Manori",
          "Materewadi",
          "Mavadi",
          "Mheluske",
          "Mohadi",
          "Mokhnal",
          "Mulane",
          "Nalegaon",
          "Nalwadi",
          "Nalwadpada",
          "Nanashi",
          "Nave Dhagur",
          "Nigdol",
          "Nilwandi",
          "Ozarkhed",
          "Oze",
          "Pade",
          "Palasvihir",
          "Palkhed Bandhara",
          "Pandane",
          "Parmori",
          "Phopshi",
          "Pimpalgaon Dhum",
          "Pimpalgaon Ketaki",
          "Pimpalnare",
          "Pimparkhed",
          "Pimpraj",
          "Pimpri Anchala",
          "Pingalwadi",
          "Pophalwade",
          "Punegaon",
          "Radtodi",
          "Rajapur",
          "Ramshej",
          "Rashegaon",
          "Rawalgaon",
          "Sadrale",
          "Sangamner",
          "Sarsale",
          "Sawarpada",
          "Shindpada",
          "Shindwad",
          "Shivnai",
          "Shiwarpada",
          "Shreeramnagar",
          "Songaon",
          "Sonjamb",
          "Talegaon Dindori",
          "Talegaon Vani",
          "Talyachapada",
          "Tetmala",
          "Thepanwadi",
          "Tilloli",
          "Tisgaon",
          "Titave",
          "Umrale Bk.",
          "Umrale Kh.",
          "Vaglud",
          "Valkhed",
          "Vanare",
          "Vani Kh.",
          "Vanjule",
          "Vare",
          "Varkhede",
          "Varvandi",
          "Vilwandi",
          "Wagdeopada",
          "Waghad",
          "Wanarwadi",
          "Zaralipada"
        ],
        "Igatpuri": [
          "Adharwad",
          "Adsare Bk",
          "Adsare Kh",
          "Adwan",
          "Ahurli",
          "Ambewadi",
          "Avachitwadi",
          "Awali Dumala",
          "Awal Khed",
          "Balayduri",
          "Balwantnagar",
          "Bambalewadi",
          "Barshingave",
          "Belgaon Kurhe",
          "Belgaon Tarhale",
          "Bhandardarawadi",
          "Bharvir Bk",
          "Bharvir Kh",
          "Bharwaj",
          "Bhavli Bk",
          "Bhavli Kh",
          "Biturli",
          "Borli",
          "Bortembhe",
          "Chinchale Khaire",
          "Dahalewadi",
          "Daundat",
          "Deole",
          "Dhamangaon",
          "Dhamani",
          "Dhargaon",
          "Dharnoli",
          "Fangulgavhan",
          "Gadgad Sangvi",
          "Gambhirwadi",
          "Garudeshwar",
          "Gavhande",
          "Ghodewadi",
          "Ghoti Bk.",
          "Ghoti Kh",
          "Girnare",
          "Gondedumala",
          "Igatpuri Gaon",
          "Igatpuri Shahar",
          "Indore",
          "Jamunde",
          "Janori",
          "Kaluste",
          "Kanad Wadi",
          "Kanchan Gaon",
          "Karhole",
          "Kawaddara",
          "Kawanai",
          "Khadked",
          "Khairgaon",
          "Khambale",
          "Khed",
          "Korapgaon",
          "Krishnanagar",
          "Kurhegaon",
          "Kurnoli",
          "Kurungwadi",
          "Kushegaon",
          "Lahamagewadi",
          "Laxminagar",
          "Maidara Dhanoshi",
          "Malunje",
          "Manikkhamb",
          "Manjargaon",
          "Manwedhe",
          "Mhasurli",
          "Modale",
          "Mogare",
          "Mukane",
          "Mundegaon",
          "Murambi",
          "Nagosali",
          "Nandadgaon",
          "Nandgaon Bk",
          "Nandgaon Sado",
          "Nandurvaidya",
          "Ninavi",
          "Nirpan",
          "Ondli",
          "Padli Deshmukh",
          "Pardeshwadi",
          "Pardevi",
          "Pimpalgaon Bhatata",
          "Pimpalgaon Dukra",
          "Pimpalgaon Ghadaga",
          "Pimpalgaon Mor",
          "Pimparisaddroddin",
          "Ramnagar",
          "Rayambe",
          "Sakur",
          "Samnere",
          "Sanjegaon",
          "Saturli",
          "Shenit",
          "Shenvad Bk",
          "Shenvad Kh",
          "Sherewadi",
          "Shevgedang",
          "Shidwadi",
          "Shirsate",
          "Somaj",
          "Sonoshi",
          "Taked Bk",
          "Taked Kh",
          "Takeghoti",
          "Talegaon Budruk",
          "Talogh",
          "Taloshi",
          "Taranganpada",
          "Thakurwadi",
          "Titoli",
          "Tringal Wadi",
          "Ubhade",
          "Umbarkon",
          "Wadivarhe",
          "Waghachi Wadi",
          "Waghere",
          "Waki",
          "Walvihir",
          "Wanjole",
          "Wasali"
        ],
        "Kalwan": [
          "Abhona",
          "Ambapur",
          "Ambika Ozar",
          "Amburdi Bk.",
          "Amburdi Kh.",
          "Amdar",
          "Asoli",
          "Athambe",
          "Babkhede",
          "Bagadu",
          "Balapur",
          "Barde",
          "Bedipada",
          "Belbare",
          "Bhadvan",
          "Bhagurdi",
          "Bhakurde",
          "Bhandane (Ha.)",
          "Bhandane Pimpale",
          "Bhendi",
          "Bhusani",
          "Bhutane Digar",
          "Bijore",
          "Bilwadi",
          "Bordaivat",
          "Chacher",
          "Chankapur",
          "Chaphapada",
          "Chinchore",
          "Dahyane Di.",
          "Dahyane (Otur)",
          "Dahyane Pale",
          "Dalwat",
          "Darebhanagi",
          "Daregaon (Ha)",
          "Daregaon Wani",
          "Dattanagar",
          "Desgaon",
          "Desrane",
          "Devali Karhad",
          "Devali Wani",
          "Dhaner Digar",
          "Dhanoli",
          "Dharde Digar",
          "Dhekale",
          "Eklahare",
          "Gangapur",
          "Gangavan",
          "Ganore",
          "Gobapur",
          "Golakhal",
          "Gopalkhadi",
          "Gosrane",
          "Hingave",
          "Hundyamokh",
          "Inshi",
          "Jaidar",
          "Jaipur",
          "Jamale Wani",
          "Jamle (Ha)",
          "Jamle Pale",
          "Jamshet",
          "Jirwade (Hatgad)",
          "Jirwade (O)",
          "Juni Bej",
          "Kakane",
          "Kalamthe",
          "Kalwan Bk.",
          "Kalwan Kh",
          "Kanashi",
          "Kanherwadi",
          "Karambhel Hatgad",
          "Karambhel (K)",
          "Karmale",
          "Katalgaon",
          "Katharedigar",
          "Khadaki",
          "Khadakwan",
          "Khardedigar",
          "Khedgaon",
          "Khirad",
          "Kosurde",
          "Koswan",
          "Kumsadi",
          "Kundane (Kanashi)",
          "Kurdane (Otur)",
          "Lakhani",
          "Lingame",
          "Machidhodap",
          "Malagaon Bk.",
          "Malagaon Kh.",
          "Manur",
          "Mehadar",
          "Mohamukh",
          "Mohandari",
          "Mohobari",
          "Mohpada",
          "Mokbhanagi",
          "Mulane Wani",
          "Nakode",
          "Nalid",
          "Nanduri",
          "Narul",
          "Navi Bej",
          "Niwane",
          "Otur",
          "Ozar",
          "Padgan",
          "Palasdar",
          "Pale Bk.",
          "Pale Kh.",
          "Patvihir",
          "Pilakos",
          "Pimple Bk.",
          "Pimple Kh.",
          "Pimpri Markand",
          "Pimpri Pale",
          "Pratapnagar",
          "Punadnagar",
          "Punegaon",
          "Ravalji",
          "Sadadvihir",
          "Sakore",
          "Sakorepada",
          "Sarale Digar",
          "Savaki Pale",
          "Savarpada",
          "Shepupada",
          "Sheri Digar",
          "Shingashi",
          "Shirasamani",
          "Shivbhandane",
          "Shrungarwadi",
          "Sidharthanagar",
          "Sptashrungi Gad",
          "Sukapur Hatgad",
          "Sule",
          "Supale (Di)",
          "Tatani",
          "Tirhal Bk.",
          "Tirhal Kh.",
          "Umbarde",
          "Vanjari",
          "Verule",
          "Virshet",
          "Visapur",
          "Vithewadipale",
          "Wadale Hatgad",
          "Wadale Wani",
          "Wadi Bk.",
          "Wadpada",
          "Warkheda"
        ],
        "Malegaon": [
          "Aghar Bk",
          "Aghar Kh",
          "Ajande Bk.",
          "Ajande Kh.",
          "Ajang",
          "Astane",
          "Belgaon",
          "Bharadenagar",
          "Bhaygaon",
          "Bhilkot",
          "Bhuigavhan",
          "Bodhe",
          "Chandanpuri",
          "Chaukatpade",
          "Chikhalohal",
          "Chinchagavhan",
          "Chinchavad",
          "Chinchave Ga.",
          "Chondhi",
          "Dabhadi",
          "Dabli",
          "Dahidi",
          "Dahikute",
          "Dahiwal",
          "Dapur",
          "Daregaon",
          "Dasane",
          "Deoghat",
          "Devarpada",
          "Dhavaeshwar",
          "Dongrale",
          "Dubagule",
          "Dundhe",
          "Dyane",
          "Erandgaon",
          "Galne",
          "Ganeshnagar (Mitranagar.)",
          "Garbad",
          "Garegaon",
          "Ghodegaon",
          "Ghodegaon Chouki",
          "Gigaon",
          "Gilane",
          "Gugulwad",
          "Hatane",
          "Hiswal Bk",
          "Jalgaon (Ga.)",
          "Jalgaon (Ni)",
          "Jalku",
          "Jatpade",
          "Jeur",
          "Jwardi Bk.",
          "Jwardi Kh",
          "Kajwade",
          "Kalewadi",
          "Kalwadi",
          "Kandhane",
          "Kankrale",
          "Karanjgavhan",
          "Kashti",
          "Kaulane (Ga.)",
          "Kaulane (N)",
          "Khadaki",
          "Khakurdi",
          "Khalane",
          "Khayade",
          "Kothare Bk.",
          "Kothare Kh.",
          "Kukane",
          "Lakhani",
          "Lendane",
          "Lonwade",
          "Lulle",
          "Malagaon",
          "Maldhe",
          "Malegaon",
          "Malegaon Camp",
          "Malhanagaon",
          "Manjare",
          "Manke",
          "Mathurpade",
          "Mehune",
          "Mohapade",
          "Mordar",
          "Mungase",
          "Nagaon Di.",
          "Nagzari",
          "Nale",
          "Nandgaon",
          "Nandgaon Kh.",
          "Nardane",
          "Nilgavhan",
          "Nimbait",
          "Nimgaon",
          "Nimgaon Kh",
          "Nimgule (Lahan)",
          "Nimgule Mothe",
          "Nimshevadi",
          "Padalde",
          "Palasdare",
          "Pandharun",
          "Patane",
          "Patharde",
          "Pimpalgaon",
          "Pohane",
          "Rajmane",
          "Rampura",
          "Ravalgaon",
          "Ronzane",
          "Roze",
          "Sajvahal",
          "Sakur",
          "Sakuri(Nimbait)",
          "Sangameshwar",
          "Satarpada",
          "Satmane",
          "Saundane",
          "Savandgaon",
          "Savkarwadi",
          "Sawatawadi",
          "Sayane Bk",
          "Sayane Kh",
          "Shendurni",
          "Sherul",
          "Shirsondi",
          "Sitane",
          "Sonaj",
          "Soyagaon",
          "Takali",
          "Talwade",
          "Tehare",
          "Tinghari",
          "Tipe",
          "Tokade",
          "Umbardhe",
          "Vadel",
          "Vadgaon",
          "Vadner",
          "Vajirkhede",
          "Vake",
          "Valwade",
          "Valwadi",
          "Vanpat",
          "Varhane",
          "Varhanepada",
          "Virane",
          "Yesgaon Bk",
          "Yesgaon Kh",
          "Zadi",
          "Zodge"
        ],
        "Nandgaon": [
          "Amode",
          "Anakwade",
          "Astagaon",
          "Azadnagar",
          "Babhulwadi",
          "Bangaon Bk.",
          "Bangaon Kh.",
          "Bejgaon",
          "Bhalur",
          "Bhardi",
          "Bhauri",
          "Birole",
          "Bolthan",
          "Borale",
          "Boygaon",
          "Chandanpuri",
          "Chandore",
          "Chinchvihir",
          "Dahegaon",
          "Darhel",
          "Dhaner",
          "Dheku Bk.",
          "Dheku Kh.",
          "Dhotane Bk.",
          "Dhotane Kh.",
          "Doctorwadi",
          "Ekwai",
          "Fulenagar",
          "Ganeshnagar",
          "Gangadhari",
          "Ghadeghewadi",
          "Girnanagar",
          "Gondegaon",
          "Hingane Dehere",
          "Hinganwadi",
          "Hirenagar",
          "Hiswal Bk.",
          "Hiswal Kh.",
          "Jalgaon Bk.",
          "Jalgaon Kh.",
          "Jamdari",
          "Jategaon",
          "Jawalki",
          "Kalamdari",
          "Karhi",
          "Kasabkhede",
          "Kasari",
          "Khadgaon",
          "Khirdipatode",
          "Kondhar",
          "Krantinagar",
          "Kusumtel",
          "Laxminagar",
          "Lodhare",
          "Lohshingve",
          "Malegaon Karyat",
          "Malgaon",
          "Malharwadi",
          "Mandwad",
          "Manglane",
          "Manikpunj",
          "Manmad 1",
          "Manmad 2",
          "Mohegaon",
          "Morzar",
          "Muldongari",
          "Nagapur",
          "Nandgaon",
          "Nandur",
          "Narayangaon",
          "Navsari",
          "Naydongari",
          "Palashi",
          "Panewadi",
          "Panzandev",
          "Pardhadi",
          "Parekarwadi",
          "Pimparkhed",
          "Pimprale",
          "Pimpri Haveli",
          "Pohi",
          "Pokhari (Pa.)",
          "Punarvasahat Panjhan (New.Panjhan)",
          "Rankhede",
          "Rohile Bk",
          "Sakora",
          "Satane",
          "Sawargaon",
          "Shashrinagar",
          "Shriramnagar",
          "Soygaon",
          "Takli Bk.",
          "Takli Kh.",
          "Talwade",
          "Tandulwadi",
          "Vanjarwadi",
          "Vasant Nagar",
          "Vehelgaon",
          "Wadali Bk.",
          "Wadali Kh.",
          "Wakhari"
        ],
        "Nashik": [
          "Aanandwalli",
          "Adgaon 1",
          "Adgaon 2",
          "Agartakli",
          "Ambad Khurd",
          "Ambebahula",
          "Babhaleshwar",
          "Belatgavhan",
          "Belgaon Dhaga",
          "Bhagur",
          "Chadegaon",
          "Chandgiri",
          "Chandshi",
          "Chehadi Budruk",
          "Chunchale",
          "Dadhegaon",
          "Dahegaon",
          "Dari",
          "Dasak",
          "Deolali 1",
          "Deolali 2",
          "Devargaon",
          "Dhondegaon",
          "Donwade",
          "Dudgaon",
          "Dugaon",
          "Eklahare",
          "Ganeshgaon Nashik",
          "Ganeshgaon Trambak",
          "Gangamhalungi",
          "Gangapadali",
          "Gangapur",
          "Gangavarhe",
          "Gaulane",
          "Girnare",
          "Govardhan",
          "Govindrur",
          "Hinganwedhe",
          "Indiranagar",
          "Jakhori",
          "Jalalpur",
          "Jategaon",
          "Kalavi",
          "Kamatwade",
          "Kotamgaon",
          "Ladchi",
          "Lahvit",
          "Lakhalgaon",
          "Lohshingve",
          "Madsangavi",
          "Mahadeopur",
          "Mahirawani",
          "Makhamalabad 1",
          "Makhamalabad 2",
          "Manoli",
          "Manur",
          "Matori",
          "Mhasrul",
          "Mohagaon",
          "Mungsare",
          "Nagalwadi",
          "Naikwadi",
          "Nandur Dasak",
          "Nanegaon",
          "Nashik Shahar 1",
          "Nashik Shahar 2",
          "Nashik Shahar 3",
          "Nashik Shahar 4",
          "Nashikshahar 5",
          "Odha",
          "Ozarkhede",
          "Palse",
          "Panchak",
          "Pathardi 1",
          "Pathardi 2",
          "Pimpalgaon Bahula",
          "Pimpalgaon Garudeshwar",
          "Pimpalgaon Khamb",
          "Pimplad Nashik",
          "Pimpri Sayyad",
          "Rahuri",
          "Raigadnagar",
          "Rajewadi",
          "Rajur Bahula",
          "Sadgaon",
          "Samangaon",
          "Sansari",
          "Sarul",
          "Satpur",
          "Sawargaon",
          "Shastrinagar",
          "Shewge Darna",
          "Shilapur",
          "Shinde",
          "Shingvebahula",
          "Shivangaon",
          "Subhashnagar",
          "Sultanpur",
          "Talegaon Anjaneri",
          "Tiradshet",
          "Vadala",
          "Vadgaon",
          "Vadner Dumala",
          "Vanjarwadi",
          "Vihitgaon",
          "Vilholi",
          "Vinchurgavali",
          "Wasali",
          "Yashwantnagar"
        ],
        "Niphad": [
          "Ahergaon",
          "Antarweli",
          "Aurangpur",
          "Banganganagar",
          "Behed",
          "Bharwas",
          "Bhendali",
          "Bhuse",
          "Bokaddare",
          "Bramhangaon Vanas",
          "Bramhangaon Vinchur",
          "Bramhanwade",
          "Chandori",
          "Chapadgaon",
          "Chatori",
          "Chehedi Kh.",
          "Chitegaon",
          "Dahegaon",
          "Darna Sangvi",
          "Datyane",
          "Davachwadi",
          "Deogaon",
          "Deopur",
          "Dhanore",
          "Dharangaon Khadak",
          "Dharangaon Veer",
          "Dindori",
          "Dixi",
          "Dongargaon",
          "Gajarwadi",
          "Golegaon",
          "Gondegaon",
          "Gondegav",
          "Gorthan",
          "Hanumannagar",
          "Jalgaon",
          "Jivhale",
          "Kalgaon",
          "Kanlad",
          "Karanjgaon",
          "Karanji Kh.",
          "Karsul",
          "Kasabe Sukene",
          "Kathargaon",
          "Khadak Malegaon",
          "Khangaon Najik",
          "Khangaonthadi",
          "Khedalezunge",
          "Khede",
          "Kokangaon",
          "Kotamgaon",
          "Kothure",
          "Kumbhari",
          "Kundewadi",
          "Kurudgaon",
          "Lalpadi",
          "Lasalgaon",
          "Lonwadi",
          "Mahadevnagar",
          "Mahajanpur",
          "Majargaon",
          "Manori Kh.",
          "Maralgoi Bk.",
          "Maralgoi Kh.",
          "Mauje Sukene",
          "Mhalsakore",
          "Mukhed",
          "Nagapur",
          "Naitale",
          "Nandgaon",
          "Nandurdi",
          "Nandur Kh.",
          "Nandur Madhyameshwar",
          "Narayangaon",
          "Narayantembhi",
          "Nimgaon Wakada",
          "Niphad",
          "Oney",
          "Ozar Gaon",
          "Ozer Township",
          "Pachore Bk.",
          "Pachore Kh.",
          "Pachorewani",
          "Palkhed",
          "Panchkeshwar",
          "Pimpalas",
          "Pimpalgaon Baswant 1",
          "Pimpalgaonbaswant 2",
          "Pimpalgaon Baswant 3",
          "Pimpalgaon Najik",
          "Pimpalgaon Nipani",
          "Pimpri",
          "Ramnagar",
          "Rampur",
          "Ranwad",
          "Rasalpur",
          "Raulas",
          "Redgaon",
          "Rui",
          "Saikhede",
          "Sakore",
          "Sarole Kh.",
          "Sarole Thadi",
          "Sawali",
          "Sawargaon",
          "Shimpi Takali",
          "Shingave",
          "Shirasgaon",
          "Shirwade Wakad",
          "Shirwadewani",
          "Shivadi",
          "Shivare",
          "Shiwapur",
          "Shriramnagar",
          "Shrirampur",
          "Sonewadi Bk.",
          "Sonewadi Kh.",
          "Songaon",
          "Subhash Nagar",
          "Sundarpur",
          "Takali Vinchur",
          "Talwade",
          "Tamaswadi",
          "Tarukhedle",
          "Thergaon",
          "Thetale",
          "Ugaon",
          "Umbarkhed",
          "Vadalinajik",
          "Vanasgaon",
          "Varhe Davna",
          "Vinchur",
          "Vishnunagar",
          "Vitthalwadi",
          "Wahegaon",
          "Wakad",
          "Wavi",
          "Welapur"
        ],
        "Peth": [
          "Aad Bk.",
          "Aad Kh.",
          "Abheti",
          "Adgaon",
          "Ambapani",
          "Ambapur",
          "Ambas",
          "Ambe",
          "Amdongra",
          "Amlon",
          "Andhrute",
          "Asarbari",
          "Badagi",
          "Bardapada",
          "Belpada",
          "Bhatvihir",
          "Bhaygaon",
          "Bhedamal",
          "Bhuwan",
          "Bilkas",
          "Bordha",
          "Borichibari",
          "Borpada",
          "Borwath",
          "Chafyachapada",
          "Chikadi",
          "Cholmukh",
          "Dabhadi",
          "Deogaon",
          "Derapada",
          "Devichamal",
          "Dhabyachapada",
          "Dhanpada",
          "Dhondmal",
          "Dhulghat",
          "Diksal",
          "Dolharmal",
          "Domkhadak",
          "Dongarshet",
          "Donwade",
          "Ekadare",
          "Fanaspada (Kha)",
          "Gandole",
          "Gangodbari",
          "Garmal",
          "Gawandh",
          "Gawandhpada",
          "Gaydhond",
          "Ghanshet",
          "Ghotwihira",
          "Gonde",
          "Hanumannagar",
          "Hanumantpada (Bhu)",
          "Hanumantpada (U.)",
          "Harangaon",
          "Hatrundi",
          "Homepada",
          "Inambari",
          "Jale",
          "Jamale",
          "Jambhulmal",
          "Jambvihir",
          "Jogmodi",
          "Junothi",
          "Kahandolpada",
          "Kakadpada",
          "Kalambari",
          "Kalampada",
          "Kalune",
          "Kapurne",
          "Karanjali",
          "Karanjkhed",
          "Kasatvihir",
          "Kayare",
          "Kelvihir",
          "Khadki",
          "Khambale",
          "Khamshet",
          "Kharpadi",
          "Khirkide",
          "Khokartale",
          "Kohor",
          "Kopurli Bk.",
          "Kopurli Kh.",
          "Kotambi",
          "Kulwandi",
          "Kumbhale",
          "Kumbharbari",
          "Lavhali",
          "Lingawane",
          "Malegaon",
          "Mangone",
          "Mankapur",
          "Mhasgan",
          "Mohadand",
          "Mohpada",
          "Murmuti",
          "Nachlondhi",
          "Nalshet",
          "Nirgude",
          "Pahuchibari",
          "Palashi Bk.",
          "Palashi Kh.",
          "Patali",
          "Pate",
          "Pawarpada",
          "Payarpada",
          "Peint",
          "Phanaspada (Co)",
          "Phanaspada(Pate)",
          "Pimpalpada",
          "Pimpalwati",
          "Raitale",
          "Rajbari",
          "Ranvihir",
          "Ruipetha",
          "Sadadpada (Ra)",
          "Sadadpada (Su)",
          "Sambarpada",
          "Sasune",
          "Savalghat",
          "Sawarna",
          "Shevkhandi",
          "Shinde",
          "Shingdari",
          "Shirale",
          "Shivshet",
          "Surgane",
          "Tilbhat",
          "Tirdhe",
          "Tondawal",
          "Toranmal",
          "Ubhidhond",
          "Umarpada (Ma)",
          "Umbardahad",
          "Umbarpada Bhuvan",
          "Umbarpada Karanjali",
          "Umbrad",
          "Usthale",
          "Vadabari",
          "Wadpada",
          "Waghyachibari",
          "Wakharpada",
          "Wangani",
          "Wazvad",
          "Wirmal"
        ],
        "Sinnar": [
          "Adwadi",
          "Agas Khind",
          "Ashapur",
          "Atkawade",
          "Aundhewadi",
          "Baragaon Pimpri",
          "Belu",
          "Bharatpur",
          "Bhatwadi",
          "Bhokani",
          "Borkhind",
          "Bramhanwade",
          "Chandrapur",
          "Chapadgaon",
          "Chas",
          "Chincholi",
          "Chondhi",
          "Dahiwadi",
          "Dapur",
          "Datli",
          "Dattanagar",
          "Deopur",
          "Deshwandi",
          "Dharangaon",
          "Dhondbar",
          "Dhondvirnagar",
          "Dhulwad",
          "Dodi Bk.",
          "Dodi Kh.",
          "Dubere",
          "Dusangwadi",
          "Eklahare",
          "Fardapur",
          "Fattepur",
          "Fulenagar",
          "Ghorwad",
          "Ghotewadi",
          "Gonde",
          "Gulapur",
          "Gulvanch",
          "Gurewadi",
          "Harsule",
          "Hivare",
          "Hiwargaon",
          "Jamgaon",
          "Jaygaon",
          "Jayprakash Nagar",
          "Jogaltembhi",
          "Kahandalwadi",
          "Kankori",
          "Karwadi",
          "Kasarwadi",
          "Kedarpur",
          "Keru Patilnagar",
          "Khadangali",
          "Khambale",
          "Khaparale",
          "Khopadi Bk.",
          "Khopadi Kh.",
          "Kirtangali",
          "Kolgaonmal",
          "Komalwadi",
          "Konambe",
          "Krishnanagar",
          "Kundewadimajre",
          "Kundewadi Mouje",
          "Laxmanpur",
          "Mahajanpur",
          "Maldhon",
          "Malegaon",
          "Manegaon",
          "Manori",
          "Maparwadi",
          "Marhal Bk.",
          "Marhal Kh.",
          "Mendhi",
          "Mirgaon",
          "Mithsagare",
          "Mohdari",
          "Mohu",
          "Musalgaon",
          "Naigaon",
          "Nalwadi",
          "Nandur Shingote",
          "Nimgaon Deopur",
          "Nimgaon Sinnar",
          "Nirhale",
          "Padali",
          "Panchale",
          "Pandhurli",
          "Pangari Bk",
          "Pangari Kh",
          "Paste",
          "Pathare Bk.",
          "Pathare Kh.",
          "Patole",
          "Patpimpri",
          "Pimpale",
          "Pimpalgaon",
          "Pimparwadi",
          "Ramnagar",
          "Rampur",
          "Sangavi",
          "Saradwadi",
          "Sawatamalinagar",
          "Sayale",
          "Shaha",
          "Shahapur",
          "Shastrinagar",
          "Shivade",
          "Shivajinagar",
          "Shrirampur",
          "Sinnar 1",
          "Sinnar 2",
          "Sinnar 3",
          "Sinnar 4",
          "Somthane",
          "Sonambe",
          "Sonari",
          "Sonewadi",
          "Songiri",
          "Suregaon",
          "Thangaon",
          "Ujjani",
          "Vadangali",
          "Vadgaon Pingala",
          "Vinchur Dalvi",
          "Wadgaon Sinnar",
          "Wadzire",
          "Waregaon",
          "Wavi"
        ],
        "Surgana": [
          "Aamda (Ba)",
          "Ahmadgavhan",
          "Alangun",
          "Alivdand",
          "Ambatha",
          "Ambepada",
          "Ambode",
          "Ambupada",
          "Amda Palsan",
          "Amzar",
          "Awalpada",
          "Baflun",
          "Bardipada",
          "Barhe",
          "Bedse",
          "Bendwal",
          "Bhadar",
          "Bhati",
          "Bhatvihir",
          "Bhavandagad",
          "Bhawada",
          "Bhegu",
          "Bhenshet",
          "Bhintghar",
          "Bhormal",
          "Bijurpada",
          "Bival",
          "Borchond",
          "Borgaon",
          "Bubli",
          "Chandrapur",
          "Chikadi",
          "Chikhali",
          "Chinchale",
          "Chinchpada",
          "Chinchpada (Ka)",
          "Chirai",
          "Dangrale",
          "Deogaon",
          "Deola",
          "Deshmukh Nagar",
          "Devaldari",
          "Dodipada",
          "Dolhare",
          "Dudhawal",
          "Durgapur",
          "Fanaspada",
          "Gadga",
          "Gahale",
          "Galbari",
          "Galwad",
          "Ganeshnagar",
          "Garmal",
          "Ghagbari",
          "Ghodambe",
          "Gondune",
          "Gopalnagar",
          "Gopalpur",
          "Guhi Jambhulpada",
          "Gurtembhi",
          "Hadkaichond",
          "Hanumantmal",
          "Harantekadi",
          "Haste",
          "Hatgad",
          "Hatrundi",
          "Hatti",
          "Hatti (Ba)",
          "Hemadpada",
          "Hiradipada",
          "Jahule",
          "Jambhulpada",
          "Jamunmatha",
          "Kahandolpada",
          "Kahandolsa",
          "Kalmane",
          "Karanjali",
          "Karanjul(Kelwan)",
          "Karanjul (Pe)",
          "Karanjul Surgana",
          "Karwande",
          "Katambi",
          "Kathipada",
          "Kelavan",
          "Khadakmal",
          "Khadki Digar",
          "Kharude",
          "Khiramani",
          "Khirdi",
          "Khobala",
          "Khobale Digar",
          "Khokari",
          "Khuntavihir",
          "Kotamba",
          "Kothula",
          "Krishnanagar",
          "Kukudmunda",
          "Kukudne",
          "Ladgaon",
          "Mahismal",
          "Malegaon",
          "Malgavhan",
          "Malgonde",
          "Mandha",
          "Mandve",
          "Mangdhe",
          "Mani",
          "Mankhed",
          "Mastemani",
          "Merdand",
          "Mhaiskhadak",
          "Modhalpada",
          "Mohapada (Chi)",
          "Mohapada (Khu)",
          "Morchonda",
          "Mothamal",
          "Murumdari",
          "Nadagdari",
          "Nagshewadi",
          "Nawapur",
          "Nimbarpada",
          "Palashet",
          "Palsan",
          "Palvihir",
          "Pangarne",
          "Patali (Pa)",
          "Payarpada",
          "Pilukpada",
          "Pimpalchond",
          "Pimpalsond",
          "Pohali",
          "Pratapgad",
          "Raghatvihir",
          "Rahude",
          "Rakshasbhuvan",
          "Ranjune",
          "Ranvihir",
          "Rasha",
          "Rokadpada",
          "Ronghane",
          "Roti",
          "Sabardara",
          "Sadudne",
          "Sajole",
          "Salbhoye",
          "Sambarkhal",
          "Sanjaynagar",
          "Sarad",
          "Sarmal",
          "Satkhamb",
          "Sayalpada",
          "Shinde",
          "Shribhuvan",
          "Shrirampur",
          "Songir",
          "Subhashnagar",
          "Suktale",
          "Sule (Va)",
          "Sundarban",
          "Surgana",
          "Suryagad",
          "Talpada",
          "Tapupada",
          "Thangaon",
          "Torandongri",
          "Ubarde (Mani)",
          "Udaldari",
          "Udaypur",
          "Udmal",
          "Umaremal",
          "Umbarde (Pa)",
          "Umbarpada Digar",
          "Umbarpada (Su)",
          "Umbarthan",
          "Umbarvihir",
          "Undohal",
          "Vadmal",
          "Vaghanakhi",
          "Vanjulpada",
          "Vijaynagar",
          "Wadpada (Ma)",
          "Wadpada (Su)",
          "Waghadi",
          "Waghdhond",
          "Walutzira",
          "Wangan (Ka)",
          "Wanganpada",
          "Wangan Sule",
          "Warambhe",
          "Zagadpada"
        ],
        "Trimbakeshwar": [
          "Adgaon",
          "Alwand",
          "Ambai",
          "Amboli",
          "Anjanneri",
          "Aswali Harsh",
          "Avhate",
          "Bafanvihir",
          "Behedpada",
          "Belpali",
          "Berwal",
          "Beze",
          "Bhagohol",
          "Bhilmal",
          "Bhutmokhada",
          "Boripada",
          "Bramhanwade",
          "Chikhalpada",
          "Chinchohol",
          "Chinchwad",
          "Chirapali",
          "Chokore",
          "Chourapada",
          "Dahalewadi",
          "Dalpatpur",
          "Dapure",
          "Deodongara",
          "Deodongari",
          "Deogaon",
          "Deola",
          "Dhadoshi",
          "Dhaytipada",
          "Dhumodi",
          "Divyachapada",
          "Dol Ohol",
          "Gadadvane",
          "Ganeshgaon Waghera",
          "Garmal",
          "Gavatha",
          "Ghodhadyachapada",
          "Goldari",
          "Gorthan",
          "Harshawadi",
          "Harsul",
          "Hatlondhi",
          "Hattipada",
          "Hirdi",
          "Holdar Nagar",
          "Jategaon Bk",
          "Jategaon Kh",
          "Kacharpada",
          "Kachurli",
          "Kadegvhan",
          "Kalamuste(Tryambak)",
          "Kalmuste",
          "Karanjpana",
          "Kas",
          "Khadakohol",
          "Khairaipali",
          "Khambale",
          "Kharoli",
          "Kharshet",
          "Kharwal",
          "Khoripada",
          "Kojoli",
          "Kone",
          "Kotambi (Harsul)",
          "Koulpoda",
          "Mahadeo Nagar",
          "Malegaon",
          "Met Chandrachi",
          "Metghar Killa",
          "Met Humbhachi",
          "Metkawara",
          "Met Yelyachi",
          "Mulegaon",
          "Mulvad",
          "Murambi",
          "Nandgaon",
          "Nandurkipada",
          "Nirgude (Harsul)",
          "Ozar Khed",
          "Pahine",
          "Pegalwadi (Nashik)",
          "Pegalwadi (Tryambak)",
          "Pimplad (Trimbak)",
          "Pmpri (Trimbak)",
          "Rajivnagar",
          "Rautmal",
          "Rayate",
          "Rohile",
          "Samundi",
          "Sapatpali",
          "Sapgaon",
          "Sapte",
          "Saraste",
          "Savarvada",
          "Sawarpada",
          "Shindpada",
          "Shirasgaon (Harsul)",
          "Shirasgaon(Tryambak)",
          "Shivaji Nagar",
          "Somnathnagar",
          "Take Deogaon",
          "Take Harsha",
          "Talegaon Trimbak",
          "Talwade (Trimbak)",
          "Thanapada",
          "Torangan(Harsul)",
          "Torangan(Tryambak)",
          "Tryambakeshwar",
          "Umbharande",
          "Vadholi",
          "Vaghera",
          "Varasvihir",
          "Vatakapada",
          "Vavi Harsha",
          "Vele",
          "Vinayaknagar",
          "Virnagar",
          "Walan",
          "Waygholpada",
          "Welunje",
          "Zarwad Bk",
          "Zarwad Kh"
        ],
        "Yevla": [
          "Adgaon Chothava",
          "Adgaon Repal",
          "Adsuregaon",
          "Agulgaon",
          "Aherwadi",
          "Ambegaon",
          "Andarsul",
          "Angangaon",
          "Ankai",
          "Ankute",
          "Antarveli",
          "Babhulgaon Bk.",
          "Babhulgaon Kh.",
          "Badapur",
          "Balapur",
          "Balhegaon",
          "Basantnagar",
          "Bharam",
          "Bhatgaon",
          "Bhaykhede",
          "Bhingare",
          "Bhulegaon",
          "Bokate",
          "Chandgaon",
          "Chichodi Bk.",
          "Chichodi Kh.",
          "Dahegaon Dhul",
          "Dahegaon Patoda",
          "Deolane",
          "Deothan",
          "Deshmane Bk.",
          "Deshmane Kh.",
          "Devargaon",
          "Devdari",
          "Dhamangaon",
          "Dhamode",
          "Dhanakwadi",
          "Dhanore",
          "Dhulgaon",
          "Dongarogaon",
          "Dugalgaon",
          "Erandgaon Bk.",
          "Erandgaon Kh.",
          "Ganeshpur",
          "Garkhede",
          "Gondgaon",
          "Gopalwadi",
          "Gorakhnagar",
          "Gujarkhede",
          "Hadap Sawargaon",
          "Jalgaon Neur",
          "Jaulke",
          "Jaydare",
          "Kanadi",
          "Kasarkhede",
          "Katarni",
          "Kautkhede",
          "Khairgavhan",
          "Khamgaon",
          "Kharvandi",
          "Khirdisathe",
          "Kolam Bk.",
          "Kolam Kh.",
          "Kolgaon",
          "Kotamgaon Bk.",
          "Kotamgaon Kh.",
          "Kusmadi",
          "Kusur",
          "Lahit",
          "Lauki Shiras",
          "Mahalkhede Chandvad",
          "Mahalkhede Pa",
          "Mamdapur",
          "Manori Bk.",
          "Matulthan",
          "Mukhed",
          "Murami",
          "Nagarsul",
          "Nagde",
          "Nandesar",
          "Nandur",
          "Naygavhan",
          "Neurgaon",
          "Nilkhede",
          "Nimgaon Madh",
          "Nyaharkhede Bk.",
          "Nyaharkhede Kh.",
          "Panhalsathe",
          "Panjarwadi",
          "Paregaon",
          "Patoda",
          "Pimpalgaon Jalal",
          "Pimpalgaon Lep",
          "Pimpalkhute Bk.",
          "Pimpalkhute Kh.",
          "Pimpalkhute Tisare",
          "Pimpri",
          "Purangaon",
          "Rahadi",
          "Rajapur",
          "Rayate",
          "Rendale",
          "Saigaon",
          "Satali",
          "Satare",
          "Satyagaon",
          "Savargaon",
          "Savkhede",
          "Shevage",
          "Shirasgaon Lauki",
          "Somthan Desh",
          "Somthan Josh",
          "Suregaon Rasta",
          "Talwade",
          "Tandulwadi",
          "Thangaon",
          "Undirwadi",
          "Vadgaon Balhe",
          "Vaghale",
          "Vaibothi",
          "Valadgaon",
          "Vikharni",
          "Visapur",
          "Yevla"
        ],
        "Nashik": ["Panchavati", "Gangapur", "Mhasrul", "Adgaon"],
        "Dindori": ["Dindori", "Palkhed", "Ozar", "Vadgaon"],
        "Niphad": ["Niphad", "Lasalgaon", "Pimpalgaon", "Kothure"],
        "Sinnar": ["Sinnar", "Wavi", "Musgaon", "Dubere"],
        "Igatpuri": ["Igatpuri", "Ghoti", "Tringalwadi"]
      },
      "Mumbai Suburban": {
        "Borivali": [
          "Aarey",
          "Akse",
          "Akurli",
          "Ambivali",
          "Bandivali",
          "Bandra",
          "Bapnala",
          "Bhandup",
          "Borivali",
          "Borla",
          "Brahmanwada",
          "Chakala",
          "Chandivali",
          "Charkop",
          "Chembur",
          "Chinchavali",
          "Dahisar",
          "Danda",
          "Darvali",
          "Devnar",
          "Dindoshi",
          "Eksar",
          "Eksar Pahadi",
          "Erangal",
          "Ghatkopar",
          "Gorai",
          "Goregaon",
          "Gundavali",
          "Gundgaon",
          "Hariyali",
          "Ismaliya",
          "Juhu",
          "Kandivali",
          "Kanheri",
          "Kanjur",
          "Kirol",
          "Klerabad",
          "Kolekalyan",
          "Kondivita",
          "Kopari",
          "Kurar",
          "Kurla",
          "Madh",
          "Magathane",
          "Mahul",
          "Majas",
          "Malad",
          "Malvani",
          "Manbudruk",
          "Mandale",
          "Mandpeshwar",
          "Mankhurd",
          "Manori",
          "Maravali",
          "Marol",
          "Maroshi",
          "Marve",
          "Mogra",
          "Mohili",
          "Mulgaon",
          "Mulund",
          "Nahur",
          "Oshiwara",
          "Pahadi Goregaon",
          "Parighakhar",
          "Parjapur",
          "Paspoli",
          "Poisar",
          "Powai",
          "Sahar",
          "Sai",
          "Saki",
          "Shimpvali",
          "Tirandaj",
          "Tungva",
          "Turbhe",
          "Vadhavali",
          "Vadhavan",
          "Valanai",
          "Varsova",
          "Vikroli",
          "Vileparle",
          "Vyarvali"
        ],
        "Andheri": [
          "Andheri",
          "Anik",
          "Asalfhe",
          "Versova",
          "Lokhandwala",
          "Marol"
        ],
        "Kurla": ["Kurla", "Sakinaka", "Jarimari"],
        "Bandra": ["Pali Hill", "Bandstand"]
      },
      "Mumbai City": {
        "A Ward": ["Colaba", "Fort"],
        "D Ward": ["Grant Road", "Tardeo"],
        "G/N Ward": ["Dadar", "Mahim"]
      }
    }
  };

  // --- Getters ---
  static List<LocalizedItem> getStates() {
    return _data.keys.map((k) => LocalizedItem(k, k, k)).toList();
  }

  static List<LocalizedItem> getDistricts(String state) {
    if (!_data.containsKey(state)) return [];
    return _data[state]!.keys.map((k) => LocalizedItem(k, k, k)).toList();
  }

  static List<LocalizedItem> getTalukas(String state, String district) {
    if (!_data.containsKey(state) || !_data[state]!.containsKey(district))
      return [];
    return _data[state]![district]!
        .keys
        .map((k) => LocalizedItem(k, k, k))
        .toList();
  }

  static List<LocalizedItem> getVillages(
      String state, String district, String taluka) {
    if (!_data.containsKey(state) ||
        !_data[state]!.containsKey(district) ||
        !_data[state]![district]!.containsKey(taluka)) return [];
    return _data[state]![district]![taluka]!
        .map((k) => LocalizedItem(k, k, k))
        .toList();
  }

  static bool isUrban(String district) => district.contains("Mumbai");
  static Future<void> loadData() async {}
}
